application: fg-navdata
version: 1
runtime: python
api_version: 1

handlers:
- url: /yaml
  static_dir: yaml
  mime_type: text/plain

- url: /js
  static_dir: js
  mime_type: text/plain

- url: /css
  static_dir: css
  mime_type: text/css

- url: /.*
  script: despatcher.py

